#pragma once

#include <WinUser.h>

namespace MyGame
{
	namespace Key
	{
		enum
		{
			Space = VK_SPACE,
			Apostrophe = VK_OEM_COMMA,
			Comma = VK_OEM_COMMA,
			Plus = VK_OEM_PLUS,
			Minus = VK_OEM_MINUS,
			Period = VK_OEM_PERIOD,
			Slash = VK_OEM_2,

			D0 = 0x30,
			D1 = 0x31,
			D2 = 0x32,
			D3 = 0x33,
			D4 = 0x34,
			D5 = 0x35,
			D6 = 0x36,
			D7 = 0x37,
			D8 = 0x38,
			D9 = 0x39,

			Semicolon = VK_OEM_1,
			Equal = VK_OEM_PLUS,

			A = 0x41,
			B = 0x42,
			C = 0x43,
			D = 0x44,
			E = 0x45,
			F = 0x46,
			G = 0x47,
			H = 0x48,
			I = 0x49,
			J = 0x4A,
			K = 0x4B,
			L = 0x4C,
			M = 0x4D,
			N = 0x4E,
			O = 0x4F,
			P = 0x50,
			Q = 0x51,
			R = 0x52,
			S = 0x53,
			T = 0x54,
			U = 0x55,
			V = 0x56,
			W = 0x57,
			X = 0x58,
			Y = 0x59,
			Z = 0x5A,

			LeftBracket = VK_OEM_4,
			Backslash = VK_OEM_5,
			RightBracket = VK_OEM_6,
			GraveAccent = VK_OEM_3,

			Escape = VK_ESCAPE,
			Enter = VK_RETURN,
			Tab = VK_TAB,
			Backspace = VK_BACK,
			Insert = VK_INSERT,
			Delete = VK_DELETE,
			Right = VK_RIGHT,
			Left = VK_LEFT,
			Down = VK_DOWN,
			Up = VK_UP,
			PageUp = VK_PRIOR,
			PageDown = VK_NEXT,
			Home = VK_HOME,
			End = VK_END,
			CapsLock = VK_CAPITAL,
			ScrollLock = VK_SCROLL,
			NumLock = VK_NUMLOCK,
			PrintScreen = VK_SNAPSHOT,
			Pause = VK_PRINT,

			F1 = VK_F1,
			F2 = VK_F2,
			F3 = VK_F3,
			F4 = VK_F4,
			F5 = VK_F5,
			F6 = VK_F6,
			F7 = VK_F7,
			F8 = VK_F8,
			F9 = VK_F9,
			F10 = VK_F10,
			F11 = VK_F11,
			F12 = VK_F12,
			F13 = VK_F13,
			F14 = VK_F14,
			F15 = VK_F15,
			F16 = VK_F16,
			F17 = VK_F17,
			F18 = VK_F18,
			F19 = VK_F19,
			F20 = VK_F20,
			F21 = VK_F21,
			F22 = VK_F22,
			F23 = VK_F23,
			F24 = VK_F24,

			N0 = VK_NUMPAD0,
			N1 = VK_NUMPAD1,
			N2 = VK_NUMPAD2,
			N3 = VK_NUMPAD3,
			N4 = VK_NUMPAD4,
			N5 = VK_NUMPAD5,
			N6 = VK_NUMPAD6,
			N7 = VK_NUMPAD7,
			N8 = VK_NUMPAD8,
			N9 = VK_NUMPAD9,
			NDecimal = VK_DECIMAL,
			NDivide = VK_DIVIDE,
			NMultiply = VK_MULTIPLY,
			NSubtract = VK_SUBTRACT,
			NAdd = VK_ADD,
			NEnter = VK_RETURN,
			NSeparator = VK_SEPARATOR,

			LeftShift = VK_LSHIFT,
			LeftControl = VK_LCONTROL,
			LeftAlt = VK_LMENU,
			LeftSuper = VK_LWIN,
			RightShift = VK_RSHIFT,
			RightControl = VK_RCONTROL,
			RightAlt = VK_RMENU,
			RightSuper = VK_RWIN
		};
	}
}